### ISSUE TITLE
update this to be compatible with the needs of stellarterm

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/ticker#2]
there are a few types of data feeds that we need:
https://github.com/irisli/stellarterm/issues/55

https://github.com/irisli/stellarterm/issues/56   (for this I think we should store the data in different resolutions not all at 15 min like iris suggests)
- 1 day
- hour 
- 15 min
- 1 min

**Comment by tomerweller** [comment]
Moving this discussion to Horizon: 
https://github.com/stellar/go/issues/94
